-- mod-version:4
--
-- Emacs-style push-mark (transient-mark-mode).
--
-- Pressing push-mark:set saves the current cursor position as the "mark".
-- Every subsequent cursor-movement command extends a selection from the mark
-- to the new cursor position, exactly like Emacs transient-mark-mode.
--
-- Default bindings:
--   ctrl+space   set or refresh the mark
--   ctrl+g       cancel mark mode (key consumed; go-to-line is NOT triggered)
--   escape       cancel mark mode and collapse selection (passes through to
--                doc:select-none which is already bound to escape)
--
-- Users may rebind via their user/init.lua:
--   keymap.unbind("ctrl+space", "push-mark:set")
--   keymap.add { ["ctrl+@"] = "push-mark:set" }
--
-- The keymap wrapper uses keymap.get_bindings() to resolve whatever the user
-- has bound, so any rebinding is respected automatically.

local core    = require "core"
local command = require "core.command"
local keymap  = require "core.keymap"
local DocView = require "core.docview"

local macos = PLATFORM == "Mac OS X"
local modkey_map = require("core.modkeys-" .. (macos and "macos" or "generic")).map

-- ---------------------------------------------------------------------------
-- State
-- ---------------------------------------------------------------------------

local mark = {
  active = false,
  doc    = nil,   -- Doc in which mark was set; used to auto-cancel on buffer switch
  line   = 1,
  col    = 1,
}

local function mark_reset()
  mark.active = false
  mark.doc    = nil
end

-- ---------------------------------------------------------------------------
-- Movement command set
--
-- All doc:move-to-* names generated by core/commands/doc.lua are listed here.
-- A stroke is treated as a "movement stroke" when at least one of its bound
-- commands appears in this set.
-- ---------------------------------------------------------------------------

local MOVEMENT_COMMANDS = {
  ["doc:move-to-previous-char"]        = true,
  ["doc:move-to-next-char"]            = true,
  ["doc:move-to-previous-line"]        = true,
  ["doc:move-to-next-line"]            = true,
  ["doc:move-to-previous-word-start"]  = true,
  ["doc:move-to-next-word-end"]        = true,
  ["doc:move-to-previous-block-start"] = true,
  ["doc:move-to-next-block-end"]       = true,
  ["doc:move-to-start-of-doc"]         = true,
  ["doc:move-to-end-of-doc"]           = true,
  ["doc:move-to-start-of-line"]        = true,
  ["doc:move-to-end-of-line"]          = true,
  ["doc:move-to-start-of-indentation"] = true,
  ["doc:move-to-start-of-word"]        = true,
  ["doc:move-to-end-of-word"]          = true,
  ["doc:move-to-previous-page"]        = true,
  ["doc:move-to-next-page"]            = true,
}

-- ---------------------------------------------------------------------------
-- Stroke helpers  (same pattern as universal_argument.lua)
-- ---------------------------------------------------------------------------

-- Modifier order must match keymap's normalize_stroke (modkeys-generic.lua).
local MODKEY_ORDER = { "ctrl", "shift", "alt", "altgr", "super" }

local function current_stroke(k)
  local parts = {}
  for _, mod in ipairs(MODKEY_ORDER) do
    if keymap.modkeys[mod] then
      table.insert(parts, mod)
    end
  end
  table.insert(parts, k)
  return table.concat(parts, "+")
end

local function stroke_matches(stroke, cmd_name)
  for _, b in ipairs(keymap.get_bindings(cmd_name) or {}) do
    if b == stroke then return true end
  end
  return false
end

-- Returns true when `stroke` is bound to at least one doc:move-to-* command.
local function is_movement_stroke(stroke)
  local cmds = keymap.map[stroke]
  if not cmds then return false end
  for _, cmd in ipairs(cmds) do
    if type(cmd) == "string" and MOVEMENT_COMMANDS[cmd] then
      return true
    end
  end
  return false
end

-- ---------------------------------------------------------------------------
-- Commands
-- ---------------------------------------------------------------------------

command.add("core.docview", {
  ["push-mark:set"] = function(dv)
    local line, col = dv.doc:get_selection()
    mark.active = true
    mark.doc    = dv.doc
    mark.line   = line
    mark.col    = col
    core.log_quiet("Mark set at %d:%d", line, col)
  end,
})

-- Predicate: only fires when mark is active, so ctrl+g falls through to
-- doc:go-to-line when mark mode is idle (same pattern as universal-argument:cancel).
command.add(function() return mark.active end, {
  ["push-mark:cancel"] = function()
    mark_reset()
    core.log_quiet("Mark deactivated")
  end,
})

-- ---------------------------------------------------------------------------
-- keymap.on_key_pressed wrapper
-- ---------------------------------------------------------------------------

local original_on_key_pressed = keymap.on_key_pressed

function keymap.on_key_pressed(k, ...)
  if not mark.active then
    return original_on_key_pressed(k, ...)
  end

  -- Modifier key presses (e.g. "left ctrl", "right shift") must always be
  -- forwarded immediately; they must not cancel mark mode.
  if modkey_map[k] then
    return original_on_key_pressed(k, ...)
  end

  -- Auto-cancel when the active buffer differs from the one where mark was set.
  local dv = core.active_view
  if not (dv and dv:extends(DocView)) or dv.doc ~= mark.doc then
    mark_reset()
    return original_on_key_pressed(k, ...)
  end

  local stroke = current_stroke(k)

  -- Escape: deactivate mark, pass through.
  -- escape is already bound to doc:select-none which will collapse the selection.
  if k == "escape" then
    mark_reset()
    return original_on_key_pressed(k, ...)
  end

  -- Cancel stroke: deactivate and consume the key.
  -- Consuming (not passing through) prevents go-to-line from also firing.
  if stroke_matches(stroke, "push-mark:cancel") then
    mark_reset()
    core.log_quiet("Mark deactivated")
    return true
  end

  -- Push-mark stroke while already active: pass through so the command
  -- re-sets the mark to the current cursor position.
  if stroke_matches(stroke, "push-mark:set") then
    return original_on_key_pressed(k, ...)
  end

  -- Movement stroke: collapse selection to head, execute, re-extend to mark.
  --
  -- Why collapse first: doc:move-to-previous-char and doc:move-to-next-char
  -- collapse an existing selection to its start/end instead of actually moving.
  -- Collapsing to a point beforehand guarantees they always perform a real move.
  if is_movement_stroke(stroke) then
    local line1, col1 = dv.doc:get_selection_idx(dv.doc.last_selection)
    dv.doc:set_selection(line1, col1)

    local result = original_on_key_pressed(k, ...)

    -- Safety check: the active view may have changed during execution.
    if mark.active and core.active_view == dv then
      local new_line, new_col = dv.doc:get_selection_idx(dv.doc.last_selection)
      -- head = new cursor pos, anchor = saved mark pos
      dv.doc:set_selection(new_line, new_col, mark.line, mark.col)
    end

    return result
  end

  -- Any other key: execute normally (with the current selection intact),
  -- then deactivate mark so subsequent movements are plain point moves.
  local result = original_on_key_pressed(k, ...)
  mark_reset()
  return result
end

-- ---------------------------------------------------------------------------
-- core.on_event wrapper
--
-- Text input deactivates mark mode.  The selection is left intact so that
-- any region the user built up is still available for an immediate copy/cut.
-- ---------------------------------------------------------------------------

local original_on_event = core.on_event

core.on_event = function(type, ...)
  if mark.active and type == "textinput" then
    mark_reset()
    core.log_quiet("Mark deactivated")
  end
  return original_on_event(type, ...)
end

-- Keybindings are centralized in configs/keymap/init.lua.
